//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review.
        /// </summary>
        internal static string AddReview {
            get {
                return ResourceManager.GetString("AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review is saved. Thank you!.
        /// </summary>
        internal static string AddReviewSuccess {
            get {
                return ResourceManager.GetString("AddReviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build route.
        /// </summary>
        internal static string BuildRoute {
            get {
                return ResourceManager.GetString("BuildRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is not loaded.
        /// </summary>
        internal static string CameraNotLoaded {
            get {
                return ResourceManager.GetString("CameraNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel login.
        /// </summary>
        internal static string CancelLogin {
            get {
                return ResourceManager.GetString("CancelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        internal static string CommentValidation {
            get {
                return ResourceManager.GetString("CommentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Vladislav Antonyuk.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger zone.
        /// </summary>
        internal static string DangerZone {
            get {
                return ResourceManager.GetString("DangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        internal static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        internal static string DeleteProfileConfirmationText {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} places nearby..
        /// </summary>
        internal static string FoundPlaces {
            get {
                return ResourceManager.GetString("FoundPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live view.
        /// </summary>
        internal static string LiveView {
            get {
                return ResourceManager.GetString("LiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading place details....
        /// </summary>
        internal static string LoadingPlaceDetails {
            get {
                return ResourceManager.GetString("LoadingPlaceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for places near you. It may take some time..
        /// </summary>
        internal static string LookingForPlaces {
            get {
                return ResourceManager.GetString("LookingForPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Mode.
        /// </summary>
        internal static string MaintenanceMode {
            get {
                return ResourceManager.GetString("MaintenanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places were found nearby. Change your location to find more places..
        /// </summary>
        internal static string NoPlacesFound {
            get {
                return ResourceManager.GetString("NoPlacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unleash the power of AI to explore and learn about places worldwide. Be it an ancient site or a modern city, World Explorer brings it to your smartphone..
        /// </summary>
        internal static string PromoText1 {
            get {
                return ResourceManager.GetString("PromoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets underlying information, history, culture, and interesting facts about any place before you even set foot there..
        /// </summary>
        internal static string PromoText2 {
            get {
                return ResourceManager.GetString("PromoText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover local cuisine, attractions, and hidden gems around your current location or your planned destination, making the exploration more exciting and convenient..
        /// </summary>
        internal static string PromoText3 {
            get {
                return ResourceManager.GetString("PromoText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize your recommendations according to your interests, and get the best out of your travel experience with World Explorer..
        /// </summary>
        internal static string PromoText4 {
            get {
                return ResourceManager.GetString("PromoText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be part of a global community of explorers who share insights and experiences, adding depth to your understanding of various places..
        /// </summary>
        internal static string PromoText5 {
            get {
                return ResourceManager.GetString("PromoText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered Exploration.
        /// </summary>
        internal static string PromoTitle1 {
            get {
                return ResourceManager.GetString("PromoTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Place Descriptions.
        /// </summary>
        internal static string PromoTitle2 {
            get {
                return ResourceManager.GetString("PromoTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Recommendations.
        /// </summary>
        internal static string PromoTitle3 {
            get {
                return ResourceManager.GetString("PromoTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized Experience.
        /// </summary>
        internal static string PromoTitle4 {
            get {
                return ResourceManager.GetString("PromoTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Insights.
        /// </summary>
        internal static string PromoTitle5 {
            get {
                return ResourceManager.GetString("PromoTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        internal static string RatingValidation {
            get {
                return ResourceManager.GetString("RatingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d like to share this place with you.
        /// </summary>
        internal static string SharePlaceText {
            get {
                return ResourceManager.GetString("SharePlaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Explorer: Exploring the world, one place at a time..
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {0:N1} m/s.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track user location.
        /// </summary>
        internal static string TrackUserLocation {
            get {
                return ResourceManager.GetString("TrackUserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get place details.
        /// </summary>
        internal static string UnableToGetPlaceDetails {
            get {
                return ResourceManager.GetString("UnableToGetPlaceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        internal static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited places.
        /// </summary>
        internal static string VisitedPlaces {
            get {
                return ResourceManager.GetString("VisitedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are near {0}.
        /// </summary>
        internal static string YouAreNear {
            get {
                return ResourceManager.GetString("YouAreNear", resourceCulture);
            }
        }
    }
}
