//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Client.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        internal static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        internal static string PromoText1 {
            get {
                return ResourceManager.GetString("PromoText1", resourceCulture);
            }
        }
        
        internal static string PromoText2 {
            get {
                return ResourceManager.GetString("PromoText2", resourceCulture);
            }
        }
        
        internal static string PromoText3 {
            get {
                return ResourceManager.GetString("PromoText3", resourceCulture);
            }
        }
        
        internal static string PromoText4 {
            get {
                return ResourceManager.GetString("PromoText4", resourceCulture);
            }
        }
        
        internal static string PromoText5 {
            get {
                return ResourceManager.GetString("PromoText5", resourceCulture);
            }
        }
        
        internal static string PromoTitle1 {
            get {
                return ResourceManager.GetString("PromoTitle1", resourceCulture);
            }
        }
        
        internal static string PromoTitle2 {
            get {
                return ResourceManager.GetString("PromoTitle2", resourceCulture);
            }
        }
        
        internal static string PromoTitle3 {
            get {
                return ResourceManager.GetString("PromoTitle3", resourceCulture);
            }
        }
        
        internal static string PromoTitle4 {
            get {
                return ResourceManager.GetString("PromoTitle4", resourceCulture);
            }
        }
        
        internal static string PromoTitle5 {
            get {
                return ResourceManager.GetString("PromoTitle5", resourceCulture);
            }
        }
        
        internal static string DeleteProfileConfirmationText {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmationText", resourceCulture);
            }
        }
        
        internal static string LookingForPlaces {
            get {
                return ResourceManager.GetString("LookingForPlaces", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string NoPlacesFound {
            get {
                return ResourceManager.GetString("NoPlacesFound", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string YouAreNear {
            get {
                return ResourceManager.GetString("YouAreNear", resourceCulture);
            }
        }
        
        internal static string LoadingPlaceDetails {
            get {
                return ResourceManager.GetString("LoadingPlaceDetails", resourceCulture);
            }
        }
        
        internal static string SharePlaceText {
            get {
                return ResourceManager.GetString("SharePlaceText", resourceCulture);
            }
        }
        
        internal static string UnableToGetPlaceDetails {
            get {
                return ResourceManager.GetString("UnableToGetPlaceDetails", resourceCulture);
            }
        }
        
        internal static string CancelLogin {
            get {
                return ResourceManager.GetString("CancelLogin", resourceCulture);
            }
        }
        
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        internal static string LiveView {
            get {
                return ResourceManager.GetString("LiveView", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string DangerZone {
            get {
                return ResourceManager.GetString("DangerZone", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        internal static string VisitedPlaces {
            get {
                return ResourceManager.GetString("VisitedPlaces", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string BuildRoute {
            get {
                return ResourceManager.GetString("BuildRoute", resourceCulture);
            }
        }
        
        internal static string CameraNotLoaded {
            get {
                return ResourceManager.GetString("CameraNotLoaded", resourceCulture);
            }
        }
        
        internal static string TrackUserLocation {
            get {
                return ResourceManager.GetString("TrackUserLocation", resourceCulture);
            }
        }
        
        internal static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        internal static string FoundPlaces {
            get {
                return ResourceManager.GetString("FoundPlaces", resourceCulture);
            }
        }
    }
}
