name: Build and deploy webapp

on:
    push:
        branches: [ main ]
        paths:
          - 'src/WebApp/**'
          - '.github/workflows/main_world-explorer_webapp.yml'
    pull_request:
        branches: [ main ]
        paths:
          - 'src/WebApp/**'
          - '.github/workflows/main_world-explorer_webapp.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:  
  VERSION: 1.0.${{github.run_number}}.0

jobs:
    buildWebApp:
        runs-on: windows-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up .NET
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: '8.x'

            -   name: Publish WebApp
                run: dotnet publish src/WebApp/WebApp.csproj -o '${{env.DOTNET_ROOT}}/webapp' /p:Version="${{ env.VERSION }}"

            -   name: Upload artifact for deployment job
                uses: actions/upload-artifact@v3
                with:
                    name: webapp
                    path: ${{env.DOTNET_ROOT}}/webapp
                    retention-days: 1

    deployWebApp:
        runs-on: windows-latest
        needs: buildWebApp
        if: github.event_name != 'pull_request'
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            -   name: Download artifact from build job
                uses: actions/download-artifact@v3
                with:
                    name: webapp

            -   uses: cschleiden/replace-tokens@v1
                env:
                    GOOGLE_SEARCH_APIKEY: ${{ secrets.GOOGLE_SEARCH_APIKEY }}
                    OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
                    AAD_B2C_CLIENT_SECRET: ${{ secrets.AAD_B2C_CLIENT_SECRET }}
                    AAD_B2C_GRAPH_CLIENT_SECRET: ${{ secrets.AAD_B2C_GRAPH_CLIENT_SECRET }}
                    AAD_B2C_CLAIMS_BASIC_AUTH_USERNAME: ${{ secrets.AAD_B2C_CLAIMS_BASIC_AUTH_USERNAME }}
                    AAD_B2C_CLAIMS_BASIC_AUTH_PASSWORD: ${{ secrets.AAD_B2C_CLAIMS_BASIC_AUTH_PASSWORD }}
                with:
                    tokenPrefix: '#{'
                    tokenSuffix: '}#'
                    files: '["**/appsettings.json"]'

            -   name: Deploy to Azure Web App
                id: deploy-to-webapp
                uses: azure/webapps-deploy@v2
                with:
                    app-name: 'world-explorer'
                    slot-name: 'Production'
                    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_649309CDF7F74F7B9D0D75A9017C1111 }}
                    package: .